version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type: chore"
      - "scope: ci"
    commit-message:
      prefix: "chore(actions)"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
