// Write src/generated/xterm-css.ts: xterm.js's stylesheet as a string, which
// the element puts in its shadow root. Generated rather than imported as CSS
// so that tsc, Bun, bundlers and JSR all read it as plain TypeScript.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const css = readFileSync(require.resolve('@xterm/xterm/css/xterm.css'), 'utf8');
const out = new URL('../src/generated/', import.meta.url);
mkdirSync(out, { recursive: true });
writeFileSync(
  new URL('xterm-css.ts', out),
  // Typed as string, or the declaration file would repeat the whole sheet.
  `// Generated by scripts/gen-css.ts from @xterm/xterm/css/xterm.css.\nconst css: string = ${JSON.stringify(css)};\nexport default css;\n`,
);
